name: file_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.9.2
  window_manager: ^0.4.2
  flutter_treeview: ^1.0.7+1
  native_context_menu_ng: ^0.0.2
  context_menus: ^2.0.0+1
  flutter_fancy_tree_view: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
